"""initial schema

Revision ID: 5211725d10a9
Revises:
Create Date: 2026-08-15

This migration defines the initial PostgreSQL schema from the current
SQLAlchemy models. The database has not yet been deployed, so this
revision intentionally represents the complete current baseline.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5211725d10a9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the complete current application schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_profiles",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "provider",
            sa.Enum(
                "OPENAI",
                "AZURE_OPENAI",
                "OLLAMA",
                "HUGGINGFACE",
                "COHERE",
                "VOYAGE_AI",
                "GOOGLE",
                name="embedding_provider",
            ),
            nullable=False,
        ),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=True),
        sa.Column("default_chunk_size", sa.Integer(), nullable=False),
        sa.Column("default_chunk_overlap", sa.Integer(), nullable=False),
        sa.Column("normalize_embeddings", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embedding_profiles")),
    )
    op.create_index(
        op.f("ix_embedding_profiles_name"), "embedding_profiles", ["name"], unique=True
    )
    op.create_index(
        op.f("ix_embedding_profiles_provider"),
        "embedding_profiles",
        ["provider"],
        unique=False,
    )
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "INACTIVE", "SUSPENDED", "ARCHIVED", name="tenant_status"
            ),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("code", name="uq_tenants_code"),
    )
    op.create_index(op.f("ix_tenants_code"), "tenants", ["code"], unique=False)
    op.create_index(op.f("ix_tenants_name"), "tenants", ["name"], unique=False)
    op.create_index(op.f("ix_tenants_status"), "tenants", ["status"], unique=False)
    op.create_table(
        "domains",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "ARCHIVED", name="domain_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id",
            name=op.f("ck_domains_not_self_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["domains.id"],
            name=op.f("fk_domains_parent_id_domains"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_domains_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domains")),
        sa.UniqueConstraint("tenant_id", "code", name="uq_domains_tenant_code"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_domains_tenant_name"),
    )
    op.create_index(op.f("ix_domains_code"), "domains", ["code"], unique=False)
    op.create_index(op.f("ix_domains_name"), "domains", ["name"], unique=False)
    op.create_index(
        op.f("ix_domains_parent_id"), "domains", ["parent_id"], unique=False
    )
    op.create_index(op.f("ix_domains_status"), "domains", ["status"], unique=False)
    op.create_index(
        op.f("ix_domains_tenant_id"), "domains", ["tenant_id"], unique=False
    )
    op.create_table(
        "vector_indexes",
        sa.Column("embedding_profile_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "provider",
            sa.Enum(
                "PINECONE",
                "PGVECTOR",
                "WEAVIATE",
                "QDRANT",
                "CHROMA",
                "MILVUS",
                name="vector_provider",
            ),
            nullable=False,
        ),
        sa.Column("index_name", sa.String(length=100), nullable=False),
        sa.Column("namespace", sa.String(length=100), nullable=True),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column(
            "storage_provider",
            sa.Enum(
                "LOCAL",
                "AWS_S3",
                "AZURE_BLOB",
                "GOOGLE_CLOUD_STORAGE",
                name="storage_provider",
            ),
            nullable=False,
        ),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["embedding_profile_id"],
            ["embedding_profiles.id"],
            name=op.f("fk_vector_indexes_embedding_profile_id_embedding_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vector_indexes")),
        sa.UniqueConstraint("provider", "index_name", name="uq_vector_provider_index"),
    )
    op.create_index(
        op.f("ix_vector_indexes_embedding_profile_id"),
        "vector_indexes",
        ["embedding_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vector_indexes_name"), "vector_indexes", ["name"], unique=True
    )
    op.create_index(
        op.f("ix_vector_indexes_provider"), "vector_indexes", ["provider"], unique=False
    )
    op.create_table(
        "knowledge_bases",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("domain_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "ARCHIVED", name="knowledge_base_status"),
            nullable=False,
        ),
        sa.Column("owner", sa.String(length=100), nullable=True),
        sa.Column("default_language", sa.String(length=10), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
            name=op.f("fk_knowledge_bases_domain_id_domains"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_knowledge_bases_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_bases")),
        sa.UniqueConstraint("tenant_id", "code", name="uq_knowledge_bases_tenant_code"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_knowledge_bases_tenant_name"),
    )
    op.create_index(
        op.f("ix_knowledge_bases_code"), "knowledge_bases", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_bases_domain_id"),
        "knowledge_bases",
        ["domain_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_bases_name"), "knowledge_bases", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_bases_status"), "knowledge_bases", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_bases_tenant_id"),
        "knowledge_bases",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("knowledge_base_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "document_type",
            sa.Enum(
                "PDF",
                "DOCX",
                "DOC",
                "TXT",
                "HTML",
                "MARKDOWN",
                "CSV",
                "XLSX",
                "PPTX",
                "JSON",
                "XML",
                "IMAGE",
                "OTHER",
                name="document_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "LOCAL",
                "URL",
                "API",
                "SHAREPOINT",
                "S3",
                "AZURE_BLOB",
                "GOOGLE_DRIVE",
                "MANUAL",
                name="document_source",
            ),
            nullable=False,
        ),
        sa.Column("source_reference", sa.String(length=255), nullable=True),
        sa.Column("owner", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "ACTIVE",
                "FAILED",
                "ARCHIVED",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f("fk_documents_knowledge_base_id_knowledge_bases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint(
            "knowledge_base_id", "title", name="uq_document_title_per_kb"
        ),
    )
    op.create_index(
        "ix_documents_kb_status",
        "documents",
        ["knowledge_base_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_knowledge_base_id"),
        "documents",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_table(
        "document_versions",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("version_label", sa.String(length=50), nullable=True),
        sa.Column("file_name", sa.String(length=512), nullable=False),
        sa.Column("file_extension", sa.String(length=20), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("storage_provider", sa.String(length=100), nullable=False),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_versions_document_id_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint(
            "document_id", "version_number", name="uq_document_version_number"
        ),
    )
    op.create_index(
        op.f("ix_document_versions_content_hash"),
        "document_versions",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_versions_document_id"),
        "document_versions",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        "ix_document_versions_document_version",
        "document_versions",
        ["document_id", "version_number"],
        unique=False,
    )
    op.create_table(
        "document_parsing_metadata",
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("parser_name", sa.String(length=100), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f(
                "fk_document_parsing_metadata_document_version_id_document_versions"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_parsing_metadata")),
        sa.UniqueConstraint(
            "document_version_id", name="uq_document_parsing_metadata_document_version"
        ),
    )
    op.create_index(
        op.f("ix_document_parsing_metadata_document_version_id"),
        "document_parsing_metadata",
        ["document_version_id"],
        unique=True,
    )
    op.create_table(
        "ingestions",
        sa.Column("document_version_id", sa.UUID(), nullable=False),
        sa.Column("embedding_profile_id", sa.UUID(), nullable=False),
        sa.Column("vector_index_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="ingestion_status",
            ),
            nullable=False,
        ),
        sa.Column("trigger_source", sa.String(length=50), nullable=False),
        sa.Column("initiated_by", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("total_chunks", sa.Integer(), nullable=False),
        sa.Column("successful_chunks", sa.Integer(), nullable=False),
        sa.Column("failed_chunks", sa.Integer(), nullable=False),
        sa.Column("total_embeddings", sa.Integer(), nullable=False),
        sa.Column("total_vectors_written", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_ingestions_document_version_id_document_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["embedding_profile_id"],
            ["embedding_profiles.id"],
            name=op.f("fk_ingestions_embedding_profile_id_embedding_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["vector_index_id"],
            ["vector_indexes.id"],
            name=op.f("fk_ingestions_vector_index_id_vector_indexes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestions")),
    )
    op.create_index(
        op.f("ix_ingestions_document_version_id"),
        "ingestions",
        ["document_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestions_embedding_profile_id"),
        "ingestions",
        ["embedding_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestions_status"), "ingestions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_ingestions_vector_index_id"),
        "ingestions",
        ["vector_index_id"],
        unique=False,
    )
    op.create_table(
        "chunks",
        sa.Column("ingestion_id", sa.UUID(), nullable=False),
        sa.Column("chunk_number", sa.Integer(), nullable=False),
        sa.Column("character_start", sa.Integer(), nullable=False),
        sa.Column("character_end", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["ingestions.id"],
            name=op.f("fk_chunks_ingestion_id_ingestions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
        sa.UniqueConstraint(
            "ingestion_id", "chunk_number", name="uq_chunk_number_per_ingestion"
        ),
    )
    op.create_index(
        op.f("ix_chunks_ingestion_id"), "chunks", ["ingestion_id"], unique=False
    )
    op.create_table(
        "pipeline_events",
        sa.Column("ingestion_id", sa.UUID(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "UPLOAD",
                "VALIDATION",
                "EXTRACTION",
                "CLEANING",
                "CHUNKING",
                "EMBEDDING",
                "INDEXING",
                "COMPLETED",
                name="pipeline_stage",
            ),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["ingestions.id"],
            name=op.f("fk_pipeline_events_ingestion_id_ingestions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_events")),
    )
    op.create_index(
        op.f("ix_pipeline_events_event_type"),
        "pipeline_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_events_ingestion_id"),
        "pipeline_events",
        ["ingestion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pipeline_events_stage"), "pipeline_events", ["stage"], unique=False
    )
    op.create_table(
        "processing_jobs",
        sa.Column("ingestion_id", sa.UUID(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "UPLOAD",
                "VALIDATION",
                "EXTRACTION",
                "CLEANING",
                "CHUNKING",
                "EMBEDDING",
                "INDEXING",
                "COMPLETED",
                name="pipeline_stage",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="processing_job_status",
            ),
            nullable=False,
        ),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["ingestions.id"],
            name=op.f("fk_processing_jobs_ingestion_id_ingestions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
    )
    op.create_index(
        op.f("ix_processing_jobs_ingestion_id"),
        "processing_jobs",
        ["ingestion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_processing_jobs_stage"), "processing_jobs", ["stage"], unique=False
    )
    op.create_index(
        op.f("ix_processing_jobs_status"), "processing_jobs", ["status"], unique=False
    )
    op.create_table(
        "embeddings",
        sa.Column("ingestion_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("vector_index_id", sa.UUID(), nullable=False),
        sa.Column("vector_identifier", sa.String(length=255), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("embedding_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["chunks.id"], name=op.f("fk_embeddings_chunk_id_chunks")
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["ingestions.id"],
            name=op.f("fk_embeddings_ingestion_id_ingestions"),
        ),
        sa.ForeignKeyConstraint(
            ["vector_index_id"],
            ["vector_indexes.id"],
            name=op.f("fk_embeddings_vector_index_id_vector_indexes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embeddings")),
        sa.UniqueConstraint(
            "chunk_id", "vector_index_id", name="uq_chunk_vector_index"
        ),
    )
    op.create_index(
        op.f("ix_embeddings_chunk_id"), "embeddings", ["chunk_id"], unique=False
    )
    op.create_index(
        op.f("ix_embeddings_ingestion_id"), "embeddings", ["ingestion_id"], unique=False
    )
    op.create_index(
        op.f("ix_embeddings_vector_identifier"),
        "embeddings",
        ["vector_identifier"],
        unique=True,
    )
    op.create_index(
        op.f("ix_embeddings_vector_index_id"),
        "embeddings",
        ["vector_index_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the complete application schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_embeddings_vector_index_id"), table_name="embeddings")
    op.drop_index(op.f("ix_embeddings_vector_identifier"), table_name="embeddings")
    op.drop_index(op.f("ix_embeddings_ingestion_id"), table_name="embeddings")
    op.drop_index(op.f("ix_embeddings_chunk_id"), table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_index(op.f("ix_processing_jobs_status"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_stage"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_ingestion_id"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index(op.f("ix_pipeline_events_stage"), table_name="pipeline_events")
    op.drop_index(op.f("ix_pipeline_events_ingestion_id"), table_name="pipeline_events")
    op.drop_index(op.f("ix_pipeline_events_event_type"), table_name="pipeline_events")
    op.drop_table("pipeline_events")
    op.drop_index(op.f("ix_chunks_ingestion_id"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_ingestions_vector_index_id"), table_name="ingestions")
    op.drop_index(op.f("ix_ingestions_status"), table_name="ingestions")
    op.drop_index(op.f("ix_ingestions_embedding_profile_id"), table_name="ingestions")
    op.drop_index(op.f("ix_ingestions_document_version_id"), table_name="ingestions")
    op.drop_table("ingestions")
    op.drop_index(
        op.f("ix_document_parsing_metadata_document_version_id"),
        table_name="document_parsing_metadata",
    )
    op.drop_table("document_parsing_metadata")
    op.drop_index(
        "ix_document_versions_document_version", table_name="document_versions"
    )
    op.drop_index(
        op.f("ix_document_versions_document_id"), table_name="document_versions"
    )
    op.drop_index(
        op.f("ix_document_versions_content_hash"), table_name="document_versions"
    )
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_knowledge_base_id"), table_name="documents")
    op.drop_index("ix_documents_kb_status", table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_knowledge_bases_tenant_id"), table_name="knowledge_bases")
    op.drop_index(op.f("ix_knowledge_bases_status"), table_name="knowledge_bases")
    op.drop_index(op.f("ix_knowledge_bases_name"), table_name="knowledge_bases")
    op.drop_index(op.f("ix_knowledge_bases_domain_id"), table_name="knowledge_bases")
    op.drop_index(op.f("ix_knowledge_bases_code"), table_name="knowledge_bases")
    op.drop_table("knowledge_bases")
    op.drop_index(op.f("ix_vector_indexes_provider"), table_name="vector_indexes")
    op.drop_index(op.f("ix_vector_indexes_name"), table_name="vector_indexes")
    op.drop_index(
        op.f("ix_vector_indexes_embedding_profile_id"), table_name="vector_indexes"
    )
    op.drop_table("vector_indexes")
    op.drop_index(op.f("ix_domains_tenant_id"), table_name="domains")
    op.drop_index(op.f("ix_domains_status"), table_name="domains")
    op.drop_index(op.f("ix_domains_parent_id"), table_name="domains")
    op.drop_index(op.f("ix_domains_name"), table_name="domains")
    op.drop_index(op.f("ix_domains_code"), table_name="domains")
    op.drop_table("domains")
    op.drop_index(op.f("ix_tenants_status"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_name"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_code"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(
        op.f("ix_embedding_profiles_provider"), table_name="embedding_profiles"
    )
    op.drop_index(op.f("ix_embedding_profiles_name"), table_name="embedding_profiles")
    op.drop_table("embedding_profiles")
    # ### end Alembic commands ###
