"""
File:
    backend/models/document_parsing_metadata.py

Purpose:
    Stores metadata produced during document parsing.

This entity is intentionally separate from DocumentVersion.

DocumentVersion stores physical file information.

DocumentParsingMetadata stores information generated by the parsing process.

Future processing stages (Chunking, Embedding, Classification, OCR, etc.)
should follow the same pattern by introducing their own metadata entities
instead of extending DocumentVersion.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from sqlalchemy import ForeignKey, Integer, String, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.models.constants import PROVIDER_NAME_LENGTH
from backend.models.entity import Entity

if TYPE_CHECKING:
    from backend.models.document_version import DocumentVersion


class DocumentParsingMetadata(Entity):
    """
    Metadata generated during document parsing.
    """

    __tablename__ = "document_parsing_metadata"

    __table_args__ = (
        UniqueConstraint(
            "document_version_id",
            name="uq_document_parsing_metadata_document_version",
        ),
    )

    # ------------------------------------------------------------------
    # Foreign Key
    # ------------------------------------------------------------------

    document_version_id: Mapped[UUID] = mapped_column(
        ForeignKey("document_versions.id"),
        nullable=False,
        unique=True,
        index=True,
    )

    # ------------------------------------------------------------------
    # Parsing Information
    # ------------------------------------------------------------------

    parser_name: Mapped[str] = mapped_column(
        String(PROVIDER_NAME_LENGTH),
        nullable=False,
    )

    page_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    word_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    document_version: Mapped["DocumentVersion"] = relationship(
        "DocumentVersion",
        back_populates="parsing_metadata",
        lazy="selectin",
    )

    # ------------------------------------------------------------------
    # Object Representation
    # ------------------------------------------------------------------

    def __repr__(self) -> str:
        return (
            "DocumentParsingMetadata("
            f"id={self.id}, "
            f"document_version_id={self.document_version_id}, "
            f"parser='{self.parser_name}')"
        )
